### ISSUE TITLE
Unexpected crashes inside library

### ISSUE THREAD

**Issue by Vladimirmlnkv** [videosdk-live/videosdk-rtc-ios-sdk-example#11]
We are using 1.2.4 version of library.

1. We have scenario where 2 users are on call. Once one of users leave call - we get crashes for both users. Crash happens once we call method leave() on instance of class Meeting.
![image](https://user-images.githubusercontent.com/7062194/156743676-1e741096-48ae-4b13-8055-58a2e585cbe2.png)

We also got the same crashes using your example project for iOS.

One time we got a little more details about this crash. (Screenshot above)
![image](https://user-images.githubusercontent.com/7062194/156743943-b268c6ac-e875-4d61-9ede-4cd3c5bf32c1.png)

2. Library crashes with the same error once App goes to background.

3. Sometimes we got random crash inside WebSocket.didRecieve(event:) method
![image](https://user-images.githubusercontent.com/7062194/156744392-2e97c4e6-a7be-4ec8-a64f-7e6cffa8672c.png)

4. We got similar crashes in WebSocked.didRecieve(event:) once one of participants disables video stream.

Looking forward hearing from you! Please, let me know if more information needed to fix this issues

**Comment by alexanderyuryev** [comment]
Do you have any progress with this issue?

**Comment by Vladimirmlnkv** [comment]
Not yet, still waiting for some response

**Comment by ParthAsodariya** [comment]
Hey, @Vladimirmlnkv, can you please try updating the pod to the latest version and check.

**Comment by alexanderyuryev** [comment]
I tested it. 
In versions 1.2.3, 1.2.5, 1.2.6 (latest) the app  crashes every time after self.meeting?.leave()
In version 1.2.2 and bellow self.meeting?.leave() works correct, but still has some random crashes in WebSocket.didRecieve(event:) method (looks like problem inside vl_mediasoup_client_ios.framework library). Some times device stuck without crash.
Tested on iPhone 11, iPhone 12 and iPad Air 2. Possible, it depends on device performance. Older device crash more often. Maybe some memory leaks.

**Comment by Vladimirmlnkv** [comment]
@ParthAsodariya @arjun-kava @rushisangani should we expect any updates on this issue in near future?

**Comment by arjun-kava** [comment]
Hey, @Vladimirmlnkv I have posted it internally, will update you here once get updated. Thanks.

**Comment by rushisangani** [comment]
@Vladimirmlnkv  @alexanderyuryev We have fixed the crash occuring on `meeting.leave()`
Please update our sdk to version **1.2.8** and let us know if fixed at your end or not.

cc: @arjun-kava @ChintanRajpara

Thanks you very much for reporting this and your valuable feedback. ✌️

**Comment by Vladimirmlnkv** [comment]
@rushisangani it got better, but it still crashes sometime. When 1 user leaves call crash happens for another user, who is left in the call. Unfortunately i cannot provide more logs, since i don't have them. I only see that it crashes on
s.delegate?.didReceive(event: event, client: s) 
<img width="1143" alt="Screenshot 2022-04-29 at 09 19 42" src="https://user-images.githubusercontent.com/7062194/165888890-c8af8941-623b-44cf-a0a1-57f4c1c5ee96.png">

**Comment by rushisangani** [comment]
@Vladimirmlnkv Thanks, we will check and let you know the update.

**Comment by rushisangani** [comment]
@Vladimirmlnkv @arjun-kava The issue should be fixed now. I made some improvements on leave meeting.
Please update the sdk to latest version `v1.2.9`
Let me know if this still occurs.

**Comment by Vladimirmlnkv** [comment]
@rushisangani Hey, thanks for the fix, but it still crashes from time to time. Same scenario -> First user leaves the meeting, second user get the crash.
<img width="1186" alt="Screenshot 2022-05-05 at 19 57 03" src="https://user-images.githubusercontent.com/7062194/166964128-c8273973-9464-44ae-a75f-112e86ece85b.png">

**Comment by ahmedbhesaniya97** [comment]
Hey @Vladimirmlnkv,
Can you provide us your device information with specific version ?

**Comment by Vladimirmlnkv** [comment]
@rushisangani @ahmedbhesaniya97 It's strange, but today it doesn't crash for me at all. I tried to leave meeting about 100 times and i didn't get the crash.
But, now i've got strange behaviour - I don't see video stream of another user after user leaves meeting and then reconnects. Library doesn't give any logs for that, i'll try to investigate more and write to you!

I guess this issue may be considered closed, since i don't get any crashes now
